import Head from "next/head";
import Divider from "../components/Divider";
import Hero from "../components/Hero";
import ShortAbout from "../components/ShortAbout";
import HighlightedFood from "../components/HighlightedFoods";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Bobs Kitchen Budapest</title>
        <meta name="description" content="Generated by Rolcsika" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <ShortAbout />

      {/* DIVIDER */}
      <Divider />

      {/* HIGHLIGHTED FOODS */}
      <HighlightedFood />
    </Layout>
  );
}
